config_name: custom
description: Custom configuration from UI
data:
  sample_rate: 16000
  audio_duration: 2.5
  n_mfcc: 40
  n_fft: 1024
  hop_length: 160
  n_mels: 128
  feature_type: mel_spectrogram
  normalize_audio: true
training:
  batch_size: 248
  epochs: 30
  learning_rate: 0.001
  early_stopping_patience: 10
  num_workers: 1
  pin_memory: true
  persistent_workers: true
  checkpoint_frequency: best_only
  save_best_only: true
model:
  architecture: resnet18
  num_classes: 2
  pretrained: true
  dropout: 0.3
  hidden_size: 128
  num_layers: 2
  bidirectional: true
augmentation:
  time_stretch_min: 0.8
  time_stretch_max: 1.2
  pitch_shift_min: -2
  pitch_shift_max: 2
  background_noise_prob: 0.5
  noise_snr_min: 5.0
  noise_snr_max: 20.0
  rir_prob: 0.25
  freq_mask_prob: 0.5
  time_mask_prob: 0.5
optimizer:
  optimizer: adamw
  weight_decay: 0.0001
  momentum: 0.9
  betas:
  - 0.9
  - 0.999
  scheduler: cosine
  warmup_epochs: 3
  min_lr: 0.0003
  step_size: 10
  gamma: 0.1
  patience: 15
  factor: 0.5
  gradient_clip: 1.0
  mixed_precision: false
loss:
  loss_function: cross_entropy
  label_smoothing: 0.05
  focal_alpha: 0.25
  focal_gamma: 2.0
  class_weights: balanced
  hard_negative_weight: 2.0
  sampler_strategy: weighted
